input:
  grid_path: "https://raw.githubusercontent.com/piksel-ina/indonesia-coastlines/main/data/raw/indonesia_10km_tiles_coast.geojson"
  modifications_path: "https://raw.githubusercontent.com/piksel-ina/indonesia-coastlines/main/data/raw/empty_modifications.geojson"
  geomorphology_path: "https://s3.ap-southeast-2.amazonaws.com/files.auspatious.com/coastlines/coastal_geomorphology.zip"

output:
  location: "s3://piksel-staging-public-data/ls_coastlines/"
  crs: "EPSG:6933"

stac:
  stac_api_url: "https://landsatlook.usgs.gov/stac-server"
  stac_collections:
    - "landsat-c2l2-sr"
  lower_scene_limit: 250
  upper_scene_limit: 2000

options:
  start_year: 1984
  end_year: 2025
  baseline_year: 2024

  tide_model: "FES2022"

  water_index: "combined"
  index_threshold: 0.0

  mask_with_hillshade: True
  hillshade_stac_catalog: "https://earth-search.aws.element84.com/v1"
  hillshade_stac_collection: "cop-dem-glo-30"
  
  use_ensemble: False
  # ensemble_model_list: 
  #   - "FES2014"
  #   - "FES2022"
  #   - "EOT20"
  #   - "TPXO9-atlas-v5-nc"
  #   - "TPXO10-atlas-v2-nc"
  #   - "GOT5.6"
  # ensemble_model_rankings: "https://files.auspatious.com/coastlines/indo_model_rank.fgb"

  mask_with_esa_wc: True

  load_buffer_distance: 1000  # in meters, ~1km; unit depends on the CRS

  lower_scene_limit: 250
  upper_scene_limit: 2000

aws:
  aws_unsigned: False
  aws_request_payer: True

use_datacube: True