name : Build Test Image and Push

env:
  # IMAGE_NAME: ${{ github.repository }}
  AWS_REGION: ap-southeast-3
  ECR_REPOSITORY: coastlines

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::686410905891:role/piksel-ecr-github-actions
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - uses: chartboost/ruff-action@v1
        with:
          src: "./coastlines"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

    # - name: Run tests in image
    #   run: |
    #       docker run --rm ${{ env.ECR_REPOSITORY }} bash -c "pip install -e /code; pip install -r /code/requirements-test.txt; pytest /code"

  push:
    permissions: write-all
    if: github.ref == 'refs/heads/main' || github.event_name == 'release'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::686410905891:role/piksel-ecr-github-actions
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get version number for tagging the image
        id: get_version
        run: |
          git fetch --all --tags
          echo "VERSION=$(git describe --tags)" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ steps.get_version.outputs.VERSION }},${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
